# Generated by Django 5.1.5 on 2025-02-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation',
            field=models.BinaryField(blank=True, default=None, help_text='The state of the conversation with the chatbot', null=True),
        ),
    ]
