# Generated by Django 5.1.5 on 2025-02-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversation_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='conversation',
        ),
    ]
